package com.itorg.rest.webservices.demoHateoas.model;

import java.io.Serializable;

import org.springframework.hateoas.RepresentationModel;

import com.fasterxml.jackson.annotation.JsonFilter;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(description="Employee table is designed to hold information about itorg employes")
public class Employee extends RepresentationModel implements Serializable{
	private static final long serialVersionUID = 1L;
	
	@ApiModelProperty(notes="The id is autogenerated")
	private Integer employeeId;
	
	@ApiModelProperty(notes="It should have at least two characters")
	private String firstName;
	
	@ApiModelProperty(notes="It should have at least two characters")
	private String lastName;
	
	@ApiModelProperty(notes="The email must have a valida format, this is the regex applied \\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}\\b")
	private String email;
	
	@ApiModelProperty(notes="The password can only be shown to the admin user")
	private String password;	
	
	public Employee(Integer employeeId, String firstName, String lastName, String email, String password) {
		super();
		this.employeeId = employeeId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.password = password;
	}

	public Integer getEmployeeId() {
		return employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Override
	public String toString() {
		return "Employee [employeeId=" + employeeId + ", firstName=" + firstName + ", lastName=" + lastName + ", email="
				+ email + "]";
	}
	
}
